const ResumeApi = [
  {
    id: 1,
    category: "education",
    year: "Savitribai Phule Pune University (2020- 2022)",
    title: "Master of Computer Science (MCS)",
    desc: "Abasaheb Garware College",
    rate: "Pursuing",
  },
  {
    id: 2,
    category: "education",
    year: "Savitribai Phule Pune University (2017 - 2020) ",
    title: "Bachelor of Computer Science (BCS)",
    desc: "Haribhai V. Desai College",
    rate: "63.40%",
  },
  {
    id: 3,
    category: "education",
    year: "The Maharashtra State Board of Secondary & Higher Secondary Education, Pune (2015 - 2017) ",
    title: "HSC",
    desc: "Bharat English High School and Junior College",
    rate: "53.53%",
  },
  {
    id: 4,
    category: "education",
    year: "The Maharashtra State Board of Secondary & Higher Secondary Education, Pune (2015 - 2017) ",
    title: "SSC",
    desc: "Modern High School",
    rate: "79.20%",
  },
  {
    id: 1,
    category: "experience",
    year: "Software Developer (2021 - 2022) ",
    title: "Brainstorm Force",
    desc: "Collaborated productively with the product team. Twitter Feed widget and also added multi-account support for Instagramin UAE(Ultimate Addons for Elementor ) plugin. Addressed and fixed complex bugs",
    rate: "4.8/5 ",
  },
  {
    id: 2,
    category: "experience",
    year: "Web Development(2020 - 2021) ",
    title: "Cortica Web Solutions PVT.LTD",
    desc: "Communicate with the customer to understand the requirements Built web pages according to customers' needs. Host the project on the company server and check domain availability according to customers' needs and make it live. Need to maintain the site. ( Made changes if the customer has some new things to showcase on the live site ).",
    rate: "4.0/5 ",
  },
  {
    id: 3,
    category: "experience",
    year: "Web Development(2017 - 2020) ",
    title: "Freelancing",
    desc: "Communicate with the customer to understand the requirements Built web pages according to customers' needs.",
    rate: " ",
  },
]

export default ResumeApi
